feat: TET-858 boolean pill
VirtusLab/tetrisly-react pull request #141
Opened 2024-05-09 10:35 UTC by golas-m

Added the boolean pill component
[Figma design](https://www.figma.com/design/4kcoCOyXVI4TIKAh60P44C/Tetrisly-Design-System-v.1.1.0?node-id=3420-42972&t=LIiPpCUH3og1AroH-0)

2024-05-09 14:33 UTC, adrian-potepa commented
The `padding-left` value is wrong for all `beforeComponent` prop values:

<img width="344" alt="Zrzut ekranu 2024-05-9 o 16 29 35" src="https://github.com/VirtusLab/tetrisly-react/assets/6291752/150e8dd0-56d5-4073-a79c-046433c6f295">

Here is image from UI:

<img width="1140" alt="Zrzut ekranu 2024-05-9 o 16 28 41" src="https://github.com/VirtusLab/tetrisly-react/assets/6291752/37f895a6-6d75-4936-a616-4202f18dc15e">

2024-05-09 14:36 UTC, adrian-potepa commented on src/components/BooleanPill/BooleanPill.tsx
> +      data-testid="boolean-pill"
Tou should add here some default `tabIndex` value to handle `:focus` and `:active` states.

2024-05-09 14:37 UTC, adrian-potepa commented on src/components/BooleanPill/BooleanPill.styles.ts
> +  minWidth: `62px`,
It's not necessary I guess 🤔

2024-05-09 14:41 UTC, adrian-potepa commented on src/components/BooleanPill/BooleanPill.props.ts
> +  onChange?: (state: boolean) => void;
I think, we should allow here to support all native react synthetic events `onClick`, 'onFocus', `onBlur` etc.
You can add here optional `tabIndex` prop type which will be needed to support `:focus` state in css.

2024-05-09 14:44 UTC, adrian-potepa commented on src/components/BooleanPill/BooleanPill.props.ts
> +  state?: 'default' | 'disabled' | 'selected';
`selected` should be as `boolean` props `isSelected`, same as `isInverted`.
In `state` props are states which cant be mixed with other one, we can set `active` and `disabled` in the same time ;)

2024-05-09 14:44 UTC, adrian-potepa requested changes
Good job! Only few small issues to work with.

2024-05-13 07:44 UTC, mwleklinski approved these changes

2024-05-13 07:44 UTC, mwleklinski commented on src/components/BooleanPill/BooleanPill.styles.ts
> +  h: `$size-small`,
no need to use \`\` you can use "" instead

2024-05-13 14:45 UTC, adrian-potepa commented
I noticed `ker` error with story:
<img width="848" alt="image" src="https://github.com/VirtusLab/tetrisly-react/assets/6291752/689323cd-bfbd-42d5-84b4-d75d0aee4b17">

2024-05-13 15:06 UTC, adrian-potepa requested changes
`key` error in stories

2024-05-14 16:16 UTC, adrian-potepa approved these changes

2024-05-15 08:42 UTC, merged